### ISSUE TITLE
There is a horizontal scrolling issue, and the icon for uploading images may appear abnormal.

### ISSUE THREAD

**Issue by enzheng128** [adamlui/chatgpt-widescreen#24]
There is a horizontal scrolling issue, and the icon for uploading images may appear abnormal.
When clicking on GPT's historical messages, the icon for uploading images becomes abnormal.
<img width="1062" alt="image" src="https://github.com/adamlui/chatgpt-widescreen/assets/64971822/799ab161-7a2f-4351-9fc4-d863717812ff">

**Comment by adamlui** [comment]
Hey @enzheng128 thank you for reporting this! What is your userscript manager (if not using browser extension) and browser? Also is the image uploading feature for Plus subscribers only?

**Comment by adamlui** [comment]
Also how did you get it to reply in Chinese by default, did you use Custom Instructions?

**Comment by enzheng128** [comment]
I used a custom command to have it respond in Chinese.
<img width="906" alt="image" src="https://github.com/adamlui/chatgpt-widescreen/assets/64971822/85466720-3bc6-4c33-bf84-4f6512b9dfc5">


I use https://www.tampermonkey.net/ userscript manager.The interface is shown in the picture below.Only Plus users have the image upload feature.
<img width="1056" alt="image" src="https://github.com/adamlui/chatgpt-widescreen/assets/64971822/7ae882b7-90c5-4929-a164-980b9d2045d9">

**Comment by adamlui** [comment]
I don't have Plus so cannot investigate what about the new upload button causes this problem. But if you inspect element and play around with the code, you can be a contributor to fix it since you have access

The function that creates the widescreen style is lines 647-660 https://github.com/adamlui/chatgpt-widescreen/blob/main/greasemonkey/chatgpt-widescreen-mode.user.js#L647C1-L660C6

In it there is some CSS selectors that are selecting the wrong thing because of this added new button, so if you can change them then it will fix it
